export const faqObj = [
"What is POTBR about?",
"Phantom of the Bank Rats is a limited edition NFT collection or unique digital collectibles living on the Solana blockchain.",
"",
"How will POTBR’s be launched?",
"The POTBR will be confirming the launch date under our announcement tab, so keep your eyes",
"Join our discord or follow us on Twitter for latest updates.",
"All POTBR's will be minted on: https://potbr.com/",
"",
"When will POTBR be reveal to buyer?",
"We will be announcing the date at the same time as Mint.",
"",
"How many NFT will be created?",
"Total of 7,777 Phantom of the Bank Rats in this collection.",
"",
"How much do POTBR cost?",
"We will be confirming the price before launch - there will be no bonding curve or price tiers",
"",
"How you will utilise your sale profit?",
"All the profit from the sales will be divide into 3 parts:",
"",
"- Future Developments, Collaboration, Community Floor Price Control, Buy-Backs, Raffles",
"- Team profit-sharing (every team member commit to buy back POTBR's with some part of our profit)",
"- Exclusive drops, and some secret plans up our sleeve for Genesis holders",
"",
"What you will do next, after sales?",
"1) Establish community - searching for community manager & discord moderator.",
"2) Some lucky holders will receive a gratitude drop",
"3) We will be setting up a community DAO and will introduce voting for holders",
"4) $CHEESE will be created, and you will be able to yield as a holder",
"5) Member exclusive merchandise",
"",
"What blockchain are these minted on?",
"NFTs are minted on compliant contracts deployed to the Solana blockchain.",
"",
"What will royalties and fees be?",
"Royalty fees will be 5% of a sale."
];